description: Schedule for Gardyn light control
trigger:
  - platform: time
    at: "06:00:00"
    id: "on"
    variables:
      brightness_pct: 70
  - platform: time
    at: "09:00:00"
    id: "off"
  - platform: time
    at: "17:00:00"
    id: "on"
    variables:
      brightness_pct: 50
  - platform: time
    at: "20:00:00"
    id: "off"
action:
  - service: light.turn_{{trigger.id}}
    target:
      entity_id: light.gardyn_light
    data: >
      {% if trigger.id == "on" %}
        {"brightness_pct": {{brightness_pct}} }
      {% else %}
        {}
      {% endif %}
mode: single
