alias: Gardyn Pump
description: Schedule for Gardyn pump control
trigger:
  - platform: time
    at: "09:30:00"
    id: "on"
  - platform: time
    at: "09:35:00"
    id: "off"
  - platform: time
    at: "16:00:00"
    id: "on"
  - platform: time
    at: "16:05:00"
    id: "off"
  - platform: time
    at: "21:00:00"
    id: "on"
  - platform: time
    at: "21:05:00"
    id: "off"
action:
  - service: fan.turn_{{trigger.id}}
    target:
      entity_id: fan.gardyn_pump
mode: queued
