alias: Gardyn Pump
description: Schedule for Gardyn pump control
trigger:
  - platform: time
    at: "09:30:00"
  - platform: time
    at: "09:35:00"
  - platform: time
    at: "16:00:00"
  - platform: time
    at: "16:05:00"
  - platform: time
    at: "21:00:00"
  - platform: time
    at: "21:05:00"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.now.strftime('%H:%M:%S') in ['09:30:00', '16:00:00',
              '21:00:00'] }}
        sequence:
          - service: light.turn_on
            entity_id: light.gardyn_pump
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.now.strftime('%H:%M:%S') in ['09:35:00', '16:05:00',
              '21:05:00'] }}
        sequence:
          - service: light.turn_off
            entity_id: light.gardyn_pump
mode: single